a=12.5
b=32
c="hii"
d='c'
e=("Amish","Verma","Hii")
f=["Bye","Everyone"]
g={"Amish":1,"Studies":2,"Python":9}
print(type(a),type(b),type(c),type(d),type(e),type(f),type(g),sep="------------")#used for showing data_type
print(type([]) is list,type([]) is not list,type(()) is tuple,type({}) is dict,type({}) is not list,sep="------")